In [ ]:
import pandas as pd

# Datos de entregas del día
entregas = {
    'Ruta': ['Cali-Norte', 'Cali-Sur', 'Yumbo-Industrial', 'Jamundí-Centro', 'Cali-Oeste'],
    'Tiempo_Estimado_Min': [30, 45, 60, 40, 35],
    'Tiempo_Real_Min': [55, 40, 110, 35, 85],
    'Costo_Envio': [50000, 45000, 80000, 38000, 42000]
}

df_logistica = pd.DataFrame(entregas)

In [3]:
df_logistica

               Ruta  Tiempo_Estimado_Min  Tiempo_Real_Min  Costo_Envio
0        Cali-Norte                   30               55        50000
1          Cali-Sur                   45               40        45000
2  Yumbo-Industrial                   60              110        80000
3    Jamundí-Centro                   40               35        38000
4        Cali-Oeste                   35               85        42000

In [4]:
# 1. Calcular la 'Desviación'
df_logistica['Desviacion'] = df_logistica['Tiempo_Real_Min'] - df_logistica['Tiempo_Estimado_Min']
df_logistica

,Ruta,Tiempo_Estimado_Min,Tiempo_Real_Min,Costo_Envio,Desviacion
0,Cali-Norte,30,55,50000,25
1,Cali-Sur,45,40,45000,-5
2,Yumbo-Industrial,60,110,80000,50
3,Jamundí-Centro,40,35,38000,-5
4,Cali-Oeste,35,85,42000,50

In [5]:
# 2. Crear la columna 'Penalización'
df_logistica['Penalizacion'] = df_logistica.apply(lambda x: x['Costo_Envio'] * 0.5 if x['Desviacion'] > 45 else (x['Costo_Envio'] * 0.20 if x['Desviacion'] > 20 else 0 ), axis=1)
df_logistica

,Ruta,Tiempo_Estimado_Min,Tiempo_Real_Min,Costo_Envio,Desviacion,Penalizacion
0,Cali-Norte,30,55,50000,25,10000.0
1,Cali-Sur,45,40,45000,-5,0.0
2,Yumbo-Industrial,60,110,80000,50,40000.0
3,Jamundí-Centro,40,35,38000,-5,0.0
4,Cali-Oeste,35,85,42000,50,21000.0

In [6]:
# 3. Calcular el 'Ingreso_Neto'
df_logistica['Ingreso_Neto'] = df_logistica['Costo_Envio'] - df_logistica['Penalizacion']
df_logistica

,Ruta,Tiempo_Estimado_Min,Tiempo_Real_Min,Costo_Envio,Desviacion,Penalizacion,Ingreso_Neto
0,Cali-Norte,30,55,50000,25,10000.0,40000.0
1,Cali-Sur,45,40,45000,-5,0.0,45000.0
2,Yumbo-Industrial,60,110,80000,50,40000.0,40000.0
3,Jamundí-Centro,40,35,38000,-5,0.0,38000.0
4,Cali-Oeste,35,85,42000,50,21000.0,21000.0

In [ ]:
df_prod.to_excel('Ejercicio 2 Análisis de Productividad y Costos.xlsx', index=False, sheet_name='Productividad')

print("Archivo guardado exitosamente.")